apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mdsdproxyhelper
  labels:
    app: mdsdproxyhelper
webhooks:
- admissionReviewVersions: ["v1"]
  name: mdsdproxyhelper.azmk8s.io
  clientConfig:
    caBundle: ${kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'}
    service:
      name: mdsdproxyhelper
      namespace: default
      path: "/mutate"
      port: 443
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
        - "kube-system"
        - "default"
  sideEffects: None
  failurePolicy: Ignore